version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: metadata_mysql
    restart: always
    environment:
      MYSQL_DATABASE: metadata_db
      MYSQL_USER: metadata_user
      MYSQL_PASSWORD: metadata_pass
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    build: .
    container_name: metadata_api
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
